# Experiment: lora_128_balanced
# Description: train lora_128 from scrath on balanced dataset
# Date: 2025-10-24

model:
  llama_path: "lmsys/vicuna-7b-v1.1"
  whisper_path: "openai/whisper-large-v2"
  beats_path: ""
  
  # Leave empty to auto-detect latest checkpoint from output_dir
  ckpt: ""
  
  # Output directory - will look for checkpoints here and save results here
  output_dir: "./experiments/salmon_grpo_/experiments/lora_128_balanced/runs"
  
  freeze_whisper: true
  freeze_beats: true
  
  use_speech_Qformer: true
  freeze_speech_QFormer: false
  window_level_Qformer: true
  num_speech_query_token: 1
  second_per_window: 0.333333
  second_stride: 0.333333
  
  speech_llama_proj_model: ""
  freeze_speech_llama_proj: false
  
  lora: true
  lora_rank: 128
  lora_alpha: 256
  lora_dropout: 0.1
  
  multi_prompt: true
  prompt_template: "USER: {}\nASSISTANT:"
  prompt_path: "src/prompts/antispoofing_prompt.json"
  test_prompt_path: "src/prompts/antispoofing_prompt.json"
  max_txt_len: 150
  end_sym: "</s>"

datasets:
  test_ann_path: "/path/to/data/salmonn/test_salmonn_140K.json"
  max_test_samples: 10000

generate:
  max_new_tokens: 150
  min_length: 1
  num_beams: 1
  do_sample: false
  temperature: 1.0
  top_p: 0.9
  repetition_penalty: 1.0
  length_penalty: 1.0

run:
  checkpoint_strategy: "last"







